### ISSUE TITLE
TypeError through gulp-rucksack index.js from gulp-concat-util

### ISSUE THREAD

**Issue by blakejwc** [vecnatechnologies/generator-torso#4]
node: v8.11.4
npm: 5.6.0
global gulp: 3.9.1

After running `yo torso project`, I got the following error at the very end:
```
added 1037 packages in 184.783s
/other/utils/n_prefix/lib/node_modules/gulp
<!> Global gulp was found. Not adding gulp as a dependency and using the global one instead. Plese call npm install gulp --save-dev if you would like to add gulp as a project dependency
[12:38:56] Using gulpfile ~/WebstormProjects/project/gulpfile.js
[12:38:56] Starting 'watch'...
[12:38:56] Starting 'build'...
[12:38:56] Starting 'clean'...
[12:38:56] Starting 'serve'...
[12:38:56] Finished 'serve' after 68 ms
[12:38:56] Finished 'watch' after 123 ms
[12:38:56] Finished 'clean' after 135 ms
[12:38:56] Starting 'copy-resources'...
Copying resources... 
[12:38:56] Starting 'build-styles'...
[12:38:57] Starting 'build-app'...
[BS] Access URLs:
 ----------------------------------
       Local: http://localhost:3000
    External: http://10.0.0.80:3000
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.0.80:3001
 ----------------------------------
[BS] Serving files from: dist

events.js:183
      throw er; // Unhandled 'error' event
      ^
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:202:9)
    at new Buffer (buffer.js:158:17)
    at Transform.stream._transform (/home/blakejwc/WebstormProjects/project/node_modules/gulp-rucksack/index.js:38:27)
    at Transform._read (_stream_transform.js:186:10)
    at Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Transform.Writable.write (_stream_writable.js:290:11)
    at write (/home/blakejwc/WebstormProjects/project/node_modules/gulp-concat-util/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/blakejwc/WebstormProjects/project/node_modules/gulp-concat-util/node_modules/readable-stream/lib/_stream_readable.js:632:7)
```

**Comment by blakejwc** [comment]
I investigated a bit more and found that https://www.npmjs.com/package/gulp-rucksack is deprecated for https://www.npmjs.com/package/gulp-postcss using https://www.rucksackcss.org/docs/#gulp.

I made these changes to the `gulpfile.js` and was able to get past the TypeError.

However, I then was faced with the following error:
```
[ERROR] {Browserify} @ Fri Aug 17 2018 16:30:29 GMT-0700 (PDT) 
Error: Cannot find module 'backbone-torso/node_modules/jquery' from '/home/blakejwc/WebstormProjects/project/app' 
[ERROR] {Browserify} @ Fri Aug 17 2018 16:30:29 GMT-0700 (PDT) 
Error: Cannot find module 'backbone-torso/node_modules/jquery' from '/home/blakejwc/WebstormProjects/project/app' 
[ERROR] {Browserify} @ Fri Aug 17 2018 16:30:29 GMT-0700 (PDT) 
Error: Cannot find module 'backbone-torso/node_modules/jquery' from '/home/blakejwc/WebstormProjects/project/node_modules/backbone' 
[ERROR] {Browserify} @ Fri Aug 17 2018 16:30:29 GMT-0700 (PDT) 
Error: Cannot find module 'backbone-torso/node_modules/jquery' from '/home/blakejwc/WebstormProjects/project/node_modules/backbone-torso/modules' 
[ERROR] {Browserify} @ Fri Aug 17 2018 16:30:29 GMT-0700 (PDT) 
Error: Cannot find module 'backbone-torso/node_modules/jquery' from '/home/blakejwc/WebstormProjects/project/node_modules/backbone-nested' 
```
I hacked in jquery buy going into `/home/blakejwc/WebstormProjects/project/node_modules/backbone-nested/package.js`, running `npm install jquery --save`, and moving jquery from the `devDependencies` to the `dependencies` and then running `npm install` in `/home/blakejwc/WebstormProjects/project/node_modules/backbone-nested`.  After this, gulp build worked...?
